# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3.5.3

      - name: Build Module
        shell: powershell
        run: |
          Get-Content .\Copy-MTPFiles.ps1 | Add-Content -Path Copy-MTPFiles.psm1
          Get-Content .\Copy-MTPFilesFunctions.ps1 | Add-Content -Path Copy-MTPFiles.psm1
          
          Update-ModuleManifest -Path .\Copy-MTPFiles.psd1 -ModuleVersion (Get-Date -Format 'yyMM.dd.HH.mm')
          
          Copy-Item -Path .\MTPFileFormat.ps1xml -Destination .
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Copy-MTPFiles
          path: |
            Copy-MTPFiles.psm1
            Copy-MTPFiles.psd1
            MTPFileFormat.ps1xml
